<?php $data =  $block->myFunction();
$isAvailable = $block->isApsPaymentMethod($data['payment']['method']);
if ($isAvailable) {
    ?>
<div>
    <h1>APS Payment Information</h1>
    <table class='data-table admin__table-primary edit-order-table'>
    <tr>
        <td><strong>Title</strong></td>
        <td><strong>Value</strong></td>
    </tr>
    <?php
    if (!empty($data)) {
        ?>
        <tr>
            <td><strong><?= $block->escapeHtml(__('Command')); ?></strong></td>
            <td>
                <?php if (isset($data['additionalData']['command'])) {
                    ?>
                    <?= $block->escapeHtml($data['additionalData']['command']); ?>
                <?php } ?>
            </td>
        </tr>
        <tr>
            <td><strong><?= $block->escapeHtml(__('Merchant Reference')); ?></strong></td>
            <td>
                <?php if (isset($data['additionalData']['merchant_reference'])) { ?>
                    <?= $block->escapeHtml($data['additionalData']['merchant_reference']); ?>
                <?php } ?>
            </td>
        </tr>
        <tr>
            <td><strong><?= $block->escapeHtml(__('Payment Option')); ?></strong></td>
            <td>
                <?php if (isset($data['additionalData']['payment_option'])) { ?>
                    <?= $block->escapeHtml($data['additionalData']['payment_option']); ?>
                <?php } ?>
            </td>
        </tr>
        <?php
        if (isset($data['additionalData']['number_of_installments'])) {
            ?>
            <tr>
                <td><strong><?= $block->escapeHtml(__('Installments')); ?></strong></td>
                <td>
                    <?= $block->escapeHtml($data['additionalData']['number_of_installments']); ?>
                </td>
            </tr>
        <?php } ?>
        <?php
        if (isset($data['additionalData']['installment_amount'])) {
            ?>
            <tr>
                <td><strong><?= $block->escapeHtml(__('Installment Amount')); ?></strong></td>
                <td>
                    <?= $block->escapeHtml($data['additionalData']['installment_amount']); ?>
                </td>
            </tr>
        <?php } ?>
        <?php
        if (isset($data['additionalData']['installment_interest'])) {
            ?>
            <tr>
                <td><strong><?= $block->escapeHtml(__('Installment Interest')); ?></strong></td>
                <td>
                    <?= $block->escapeHtml($data['additionalData']['installment_interest']); ?>
                </td>
            </tr>
            <?php } ?>
            <?php
        
            if ($data['payment']['method'] == \Amazonpaymentservices\Fort\Model\Method\Valu::CODE) {
                ?>
            <tr>
                <td><strong><?= $block->escapeHtml(__('Tenure')); ?></strong></td>
                <td>
                    <?php if (isset($data['additionalData']['valu_tenure'])) { ?>
                        <?= $block->escapeHtml($data['additionalData']['valu_tenure']); ?>
                    <?php } ?>
                </td>
            </tr>
            <tr>
                <td><strong><?= $block->escapeHtml(__('Tenure Amount')); ?></strong></td>
                <td>
                    <?php if (isset($data['additionalData']['valu_tenure_amount'])) { ?>
                        <?= $block->escapeHtml($data['additionalData']['valu_tenure_amount']); ?>
                    <?php } ?>
                </td>
            </tr>
            <tr>
                <td><strong><?= $block->escapeHtml(__('Admin Fee')); ?></strong></td>
                <td>
                    <?php if (isset($data['additionalData']['valu_tenure_interest'])) { ?>
                        <?= $block->escapeHtml($data['additionalData']['valu_tenure_interest']); ?>
                        <?php } ?>
                </td>
            </tr>
                <?php
            }
            ?>
        <tr>
            <td><strong><?= $block->escapeHtml(__('Response Code')); ?></strong></td>
            <td>
                <?php if (isset($data['additionalData']['response_code'])) { ?>
                    <?= $block->escapeHtml($data['additionalData']['response_code']); ?>
                    <?php } ?>
            </td>
        </tr>
        <tr>
            <td><strong><?= $block->escapeHtml(__('Acquier Response Code')); ?></strong></td>
            <td>
                <?php if (isset($data['additionalData']['acquirer_response_code'])) { ?>
                    <?= $block->escapeHtml($data['additionalData']['acquirer_response_code']); ?>
                    <?php } ?>
            </td>
        </tr>
        <tr>
            <td><strong><?= $block->escapeHtml(__('Reconciliation Reference')); ?></strong></td>
            <td>
                <?php if (isset($data['additionalData']['reconciliation_reference'])) { ?>
                    <?= $block->escapeHtml($data['additionalData']['reconciliation_reference']); ?>
                <?php } ?>
            </td>
        </tr>
        <tr>
            <td><strong><?= $block->escapeHtml(__('Acquirer Response Message')); ?></strong></td>
            <td>
                <?php if (isset($data['additionalData']['acquirer_response_message'])) { ?>
                    <?= $block->escapeHtml($data['additionalData']['acquirer_response_message']); ?>
                <?php } ?>
            </td>
        </tr>
        <?php if (isset($data['additionalData']['third_party_transaction_number'])) : ?>
            <tr>
                <td><strong><?= $block->escapeHtml(__($data['additionalData']['payment_option'] . ' third party transaction number')); ?></strong></td>
                <td>
                    <?= $block->escapeHtml($data['additionalData']['third_party_transaction_number']); ?>
                </td>
            </tr>
        <?php endif ?>
        <?php if (isset($data['additionalData']['knet_ref_number'])) : ?>
            <tr>
                <td><strong><?= $block->escapeHtml(__('KNET Reference Number')); ?></strong></td>
                <td>
                    <?= $block->escapeHtml($data['additionalData']['knet_ref_number']); ?>
                </td>
            </tr>
        <?php endif ?>
    <?php } ?>
    </table>
</div>
<?php } ?>
