<?php
/** @var \Amazonpaymentservices\Fort\Block\Adminhtml\System\Config\Field\HostToHostUrl $block */
/** @var Magento\Framework\View\TemplateEngine\Php $this */
?>
<tr id="row_payment_us_aps_fort_host_to_host_url">
    <td class="label">
        <label for="payment_us_aps_fort_order_status_on_fail"><?= /* @noEscape */ __('Subscription Cron Command');?></label>
    </td>
    <td class="value"><?= /* @noEscape */ $block->getCronCommand();?></td>
</tr>
