<?php
/** @var \Payfort\Fort\Block\Adminhtml\System\Config\Field\hostToHostUrl $block */
/** @var Magento\Framework\View\TemplateEngine\Php $this */
?>
<tr id="row_payment_us_payfort_fort_host_to_host_url">
    <td class="label">
        <label for="payment_us_payfort_fort_order_status_on_fail"><?php echo __('Host to Host URL')?></label>
        <td class="value"><?php echo $block->getHostUrl()?></td>
    </td>
</tr>
