<?php
   /** @var \Amazonpaymentservices\Fort\Block\Payment\Redirect $block */

    $form_data = $block->getFormData();
    $form_url = $block->getFormUrl();
?>
<div class="apsfort-checkout">
    <?php
    if ($block->getOrderOk()) {
        
        ?>
        <div class="pf-iframe-background" id="div-pf-iframe">
            <div class="pf-iframe-container">
                <span class="pf-close-container">
                    <i class="fa fa-times-circle pf-iframe-close" onclick="apsFortStandard.closePopup()" style="display:none"></i>
                </span>
                <i class="fa fa-spinner fa-spin pf-iframe-spin"></i>
                <div class="pf-iframe" id="pf_iframe_content"></div>
            </div>
        </div>
        <form name="aps_payment_form" id="aps_payment_form" method="post" action="<?= $block->escapeHtml($form_url); ?>" style="display:none">
            <!-- general parameters -->
            <?php
            $form_data['form_key'] = 'abcd';
            foreach ($form_data as $k => $v): ?>
                <input type="hidden" name="<?= $block->escapeHtml($k); ?>" value="<?= $block->escapeHtml($v); ?>">
            <?php endforeach; ?>
        </form>
        
        <input type="hidden" id="aps_cancel_url" value="<?= $block->escapeHtml($block->getUrl('amazonpaymentservicesfort/payment/orderCancel'))?>"/>
        <script type="text/javascript">
            require(['jquery', 'aps_fort'],function($){
                'use strict';
                $(document).ready(function ($) {
                    $('#aps_payment_form input[name=form_key]').attr("disabled", "disabled");
                    var gatewayUrl = $('#aps_payment_form').attr('action');
                    apsFortStandard.showStandard(gatewayUrl);
                });
            });
        </script>
        <?php
    }
    ?>
</div>