<?php
    /** @var \Amazonpaymentservices\Fort\Block\Payment\Redirect $block */

    $form_data = $block->getFormData();
    $form_url = $block->getFormUrl();
?>
<div class="apsfort-checkout">
    <?php
    if( !$block->getOrderOk() && !empty($block->getOrderId()) )
    {
        ?>
        <p><?php echo $block->getErrorMessage()?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
            </div>
        </div>
        <?php
    } else if($block->getOrderOk()) {
        
        ?>
        <p><?= $block->escapeHtml(__('Processing order #%1... Please wait.', $block->getOrderId())) ?></p>
        
        <img src="<?= $block->escapeHtml($block->getViewFileUrl('Amazonpaymentservices_Fort::images/ajax-loader.gif')) ;?>" /><br/>
        <?= $block->escapeHtml(__('Redirecting...'));?>
        <form id="frm_aps_fort_redirect" action="<?= $block->escapeHtml($form_url);?>" method="POST" style="display: none">
        <?php
        $form_data['form_key'] = 'abcd';
        foreach ($form_data as $k => $v): ?>
            <input type='hidden' name='<?= $block->escapeHtml($k);?>' value='<?= $block->escapeHtml($v);?>' /><br>
        <?php endforeach; ?>
        </form>
        <input type="hidden" id="aps_cancel_url" value='<?= $block->escapeHtml($block->getCancelUrl()); ?>' />
        <script type="text/javascript">
            require([
                'jquery'
            ], function(jQuery) {
                jQuery(document).ready(function ($) {
                    $('#frm_aps_fort_redirect input[name=form_key]').attr("disabled", "disabled");
                    jQuery('#frm_aps_fort_redirect').submit();
                });
            });
        </script>
        <?php
    }
    ?>
</div>
